<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1</InformationalVersion>
    <Product>LanTodo</Product>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
